"""add username, first_name, last_name to users

Revision ID: 1be4919f2147
Revises: 6ea8882fa0a0
Create Date: 2025-11-14 17:51:48.765415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be4919f2147'
down_revision: Union[str, Sequence[str], None] = '6ea8882fa0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=250), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=250), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=250), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
