"""Add tags, created_by to stories and role to users

Revision ID: 3e9bf2fb2455
Revises: 1be4919f2147
Create Date: 2025-11-16 19:10:04.734526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9bf2fb2455'
down_revision: Union[str, Sequence[str], None] = '1be4919f2147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('tags', sa.String(length=500), nullable=True))
    op.add_column('stories', sa.Column('created_by', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('stories', 'created_by')
    op.drop_column('stories', 'tags')
    # ### end Alembic commands ###
